-- ============================================================
--  dripdrip — admin activity log
--  Run in Supabase → SQL Editor (after accounts.sql).
--  Records who did what, and when, in the admin panel.
-- ============================================================

create table if not exists public.activity_log (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  actor_email text,
  action      text,
  detail      text
);

alter table public.activity_log enable row level security;

-- Only admins can write to or read the log.
drop policy if exists "admin write log" on public.activity_log;
create policy "admin write log" on public.activity_log
  for insert to authenticated with check (public.is_admin());

drop policy if exists "admin read log" on public.activity_log;
create policy "admin read log" on public.activity_log
  for select to authenticated using (public.is_admin());

create index if not exists activity_log_created_idx on public.activity_log (created_at desc);

notify pgrst, 'reload schema';
