-- ============================================================
--  dripdrip — newsletter subscribers
--  Run in Supabase → SQL Editor (after accounts.sql).
--  Anyone can subscribe; only admins can read the list. New rows are
--  streamed to hermes, which sends the welcome email.
-- ============================================================

create table if not exists public.subscribers (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email      text unique
);

alter table public.subscribers enable row level security;

drop policy if exists "public can subscribe" on public.subscribers;
create policy "public can subscribe" on public.subscribers
  for insert to public with check (true);

drop policy if exists "admin read subscribers" on public.subscribers;
create policy "admin read subscribers" on public.subscribers
  for select to authenticated using (public.is_admin());

-- stream new subscribers to the hermes listener (for the welcome email)
alter publication supabase_realtime add table public.subscribers;

notify pgrst, 'reload schema';
